### ISSUE TITLE
http://michaelshaw.io/game_talk/game.html is not working

### ISSUE THREAD

**Issue by caeus** [MichaelShaw/game_example#1]
Sorry, I should've found a different place to contact you.
Anyway, I'm interested in that content but the page doesn't seem to work properly

**Comment by MichaelShaw** [comment]
Hi,

What platform are you on? 

It works on pc/mac/iPhone for me, though the PNGs cause a pretty horrible experience on iPhone when they're loading. The problem is likely that there's 50MB of png screenshots interspersed between the slides.

I'll see how it looks with some more reasonablty sized jpgs.

**Comment by caeus** [comment]
Yep, I was kinda retarded there. It works with the arrows, sorry!
